### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hillarysanders** [hillarysanders/notes#72]
- [ ] ideally get the Rscript cron job working too, it just can't find the packages yet.
- [x] get dedupe cron job working, it was broken.
- [x] increase default vendors list
- [x] make roc curve autoscale y axis
---
- [ ] run more query validation?
- [ ] start in on the v3 redshift design doc
  - is sha for the main table actually efficient for our queries? Wouldn't it be better to sort by fs_t, then report_t? fs_t in essence sorts by sha, as shas are 1-1 with fs_t. Figure out if that would be better by running a test.

- [x] DEPLOY to prod - remember to merge with the c_models branch, needs that to work.. Also need to make sure all our usernames still exist, though blowing away some db or another might be neccessary
- [x] better type for PE - use full list
