### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hillarysanders** [hillarysanders/notes#78]
- [x] got the intermediary table working with multiple data sources and aggregate labels - just need to add in models and PUA clustering. I'm still not convinced we shouldn't have 1 table per data type... Hm. So many empty columns.
- [x] fixed date thing in the dashboard.

- [x] create URL table with correct sortkeys and table name
- [x] give cody sample URL data from URL table
- [x] review Cody's callback code
- [ ] buy blackhat plane tickets
- [x] create redshift v3 design doc
   - [ ] make sure it's OK that first and last report_t = fs_t and ls_t for labsrep AND VT
- [ ] integrate Rich's blackhat comments
---
#### Later
- [ ] create cron job to delete URLs over 6mo old
- [ ] optimize inner join subqueries to use windows, might be faster ("you can do two windows at same time, one ASC and other DESC and then pick entry that has is_first =1 or is_last=1")

**Comment by hillarysanders** [comment]
flattened_t = max of that
