### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hillarysanders** [hillarysanders/notes#79]
## Core Goals
- [ ] look at K's query recommendation to see if it would help
- [x] add is_pe column to intermediary table
- [ ] create intermediary table cron job
- [ ] create intermediary table documentation
- [ ] fix vacuum code.
     - [ ] add analyze to vacuum code
     - [ ] change table owners, then change vacuum from master to this new user
- [ ] change dashboard to use g_dashboard connection (readonly but has larger concurrency for better scalability)
### Random
- [x]  integrate Rich's blackhat comments
- [ ] buy blackhat plane tickets
- [ ] create cron job to delete URLs over 6mo old
- [ ] optimize inner join subqueries to use windows, might be faster ("you can do two windows at same time, one ASC and other DESC and then pick entry that has is_first =1 or is_last=1")

**Comment by hillarysanders** [comment]
when we get a file: goes into 2 buckets: original JSON, other one is w/ PII removed. Original gets deleted after 3 months. Redshift gets PII but we create cron job to delete (transform to NULL) PII columns in redshift older than 6 months.
